apiVersion: v1
kind: Pod
metadata:
  name: nodejs
  labels:
    app: nodejs
spec:
  containers:
    - name: front-end
      image: 937420187547.dkr.ecr.ap-south-1.amazonaws.com/nodejs:samplenodejs.latest
      ports:
        - containerPort: 3000
